variables:
  TAGGER_IMAGE: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/integrations-core:tagger
  TAGGER_EMAIL: packages@datadoghq.com
  TAGGER_NAME: ci.integrations-extras

stages:
  - release

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^\[Release\] Update metadata/
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

release-auto:
  stage: release
  image: $TAGGER_IMAGE
  script:
    - ddev --version
    - ddev config set repos.extras .
    - ddev config set repo extras
    # ssh-agent performed in the main script to be persisted
    - eval "$(ssh-agent -s)"
    - ./.gitlab/release/git-auth.sh
    # Prefix every line with a timestamp
    - ./.gitlab/release/tag-release.sh 2>&1 | ts "[%H:%M:%S %Z]  "
  tags: [ "runner:main", "size:large" ]
