[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.11"]

[envs.default.env-vars]
FIDDLER_API_KEY = "23423423423423"

[envs.default]
dependencies = ["requests-mock==1.9.2"]
e2e-env = false
