[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.9"]

[envs.default.env-vars]
FIDDLER_API_KEY = "23423423423423"

[envs.default]
dependencies = ["fiddler-client==1.5.2"]
e2e-env = false
