[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.11"]
version = ["23.1"]

[envs.default.overrides]
matrix.version.env-vars = [
  { key = "REDPANDA_VERSION", value = "v23.1.10", if = ["23.1"] },
]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"

[envs.default]
e2e-env = false
