schedules:
- cron: 0 5 * * *
  displayName: Nightly (EDT/EST)
  always: true
  branches:
    include:
    - master
pr: none
trigger:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: integrations-core
    type: github
    name: Datadog/integrations-core
    ref: master
    endpoint: DataDog
  containers:
  - container: dd_agent
    image: gcr.io/datadoghq/agent:latest
    ports:
    - 8127:8126
    env:
      DD_API_KEY: $(DD_CI_API_KEY)
      DD_HOSTNAME: none
      DD_INSIDE_CI: 'true'
variables:
  DDEV_COLOR: 1
  DD_TRACE_AGENT_PORT: 8127
jobs:
- template: .azure-pipelines/templates/test-all.yml@integrations-core
  parameters:
    ddtrace_flag: --ddtrace
    repo: extras
    checks:
    - checkName: aqua
      displayName: Aqua
      os: linux
    - checkName: aws_pricing
      displayName: AWS Pricing
      os: linux
    - checkName: bind9
      displayName: BIND 9
      os: linux
    - checkName: cert_manager
      displayName: cert-manager
      os: linux
    - checkName: cfssl
      displayName: cfssl
      os: linux
    - checkName: cloudsmith
      displayName: Cloudsmith
      os: linux
    - checkName: cyral
      displayName: Cyral
      os: linux
    - checkName: eventstore
      displayName: Eventstore
      os: linux
    - checkName: exim
      displayName: exim
      os: linux
    - checkName: filebeat
      displayName: Filebeat
      os: linux
    - checkName: fluentbit
      displayName: Fluent Bit
      os: linux
    - checkName: flume
      displayName: flume
      os: linux
    - checkName: gatekeeper
      displayName: Gatekeeper
      os: linux
    - checkName: gitea
      displayName: Gitea
      os: linux
    - checkName: gnatsd
      displayName: Gnatsd
      os: linux
    - checkName: gnatsd_streaming
      displayName: Gnatsd Streaming
      os: linux
    - checkName: jfrog_platform
      displayName: JFrog Platform
      os: linux
    - checkName: kernelcare
      displayName: Kernelcare
      os: linux
    - checkName: lighthouse
      displayName: Lighthouse
      os: linux
    - checkName: logstash
      displayName: Logstash
      os: linux
    - checkName: neo4j
      displayName: Neo4j
      os: linux
    - checkName: neutrona
      displayName: Neutrona
      os: linux
    - checkName: nextcloud
      displayName: Nextcloud
      os: linux
    - checkName: nn_sdwan
      displayName: Netnology SD-WAN
      os: linux
    - checkName: ns1
      displayName: NS1
      os: linux
    - checkName: nvml
      displayName: nvml
      os: linux
    - checkName: octoprint
      displayName: OctoPrint
      os: linux
    - checkName: open_policy_agent
      displayName: open_policy_agent
      os: linux
    - checkName: php_apcu
      displayName: PHP APCu
      os: linux
    - checkName: php_opcache
      displayName: PHP OPcache
      os: linux
    - checkName: pihole
      displayName: pihole
      os: linux
    - checkName: ping
      displayName: Ping
      os: linux
    - checkName: portworx
      displayName: Portworx
      os: linux
    - checkName: pulsar
      displayName: pulsar
      os: linux
    - checkName: puma
      displayName: Puma
      os: linux
    - checkName: purefa
      displayName: PureFA
      os: linux
    - checkName: purefb
      displayName: PureFB
      os: linux
    - checkName: reboot_required
      displayName: Reboot Required
      os: linux
    - checkName: redis_sentinel
      displayName: Redis Sentinel
      os: linux
    - checkName: redisenterprise
      displayName: Redis Enterprise
      os: linux
    - checkName: redpanda
      displayName: Redpanda
      os: linux
    - checkName: resin
      displayName: Resin
      os: linux
    - checkName: riak_repl
      displayName: Riak MDC Replication
      os: linux
    - checkName: sendmail
      displayName: Sendmail
      os: linux
    - checkName: snmpwalk
      displayName: Snmpwalk
      os: linux
    - checkName: sortdb
      displayName: Sortdb
      os: linux
    - checkName: speedtest
      displayName: speedtest
      os: linux
    - checkName: stardog
      displayName: Stardog
      os: linux
    - checkName: storm
      displayName: Storm
      os: linux
    - checkName: syncthing
      displayName: Syncthing
      os: linux
    - checkName: tidb
      displayName: TiDB
      os: linux
    - checkName: traefik
      displayName: Traefik
      os: linux
    - checkName: trino
      displayName: Trino
      os: linux
    - checkName: unbound
      displayName: Unbound
      os: linux
    - checkName: upsc
      displayName: UPSC
      os: linux
    - checkName: vespa
      displayName: Vespa
      os: linux
    - checkName: zabbix
      displayName: Zabbix
      os: linux
