[overrides.display-name]
contrastsecurity = "Contrast Security"
gnatsd_streaming = "Gnatsd Streaming"
reboot_required = "Reboot Required"
storm = "Storm"

[overrides.metrics-prefix]
aerospike_enterprise = "aerospike."
snmpwalk = "snmpwalk."
